---
- name: update apt databae
  apt:
    update_cache: yes
  become: yes

- name: install LXQt desktop environment
  package:
    name: task-lxqt-desktop
    state: present
  notify: start sddm
  become: yes

- name: ensure /etc/sddm.conf.d existis
  file:
    path: /etc/sddm.conf.d
    state: directory
  become: yes

- name: enable LXQt autologin
  copy:
    content: |
      [Autologin]
      User={{ ansible_env.USER }}
      Session=lxqt.desktop
      Relogin=false
    dest: /etc/sddm.conf.d/autologin
  become: yes

- name: disable some LXQt autostarts
  lineinfile:
    path: /etc/xdg/autostart/{{ item }}.desktop
    regexp: '^Hidden='
    line: 'Hidden=true'
  loop:
  - lxqt-powermanagement
  - lxqt-xscreensaver-autostart
  become: yes
