[General]
network = artery.inet.World

# Works nicely with backwards. Just make sure that
# stack unwinding does not crash the kernel :)
debug-on-errors = true

cmdenv-express-mode = false
cmdenv-event-banners = false
cmdenv-autoflush = true

cmdenv-output-file = ".cmdenv-log"
**.cmdenv-log-level = debug

**.scalar-recording = true
**.vector-recording = true
outputscalarmanager-class = "omnetpp::envir::SqliteOutputScalarManager"
outputvectormanager-class = "omnetpp::envir::SqliteOutputVectorManager"
output-scalar-file = ${resultdir}/${configname}-${runnumber}-scalars.sqlite
output-vector-file = ${resultdir}/${configname}-${runnumber}-vectors.sqlite


*.withPhysicalEnvironment = true

*.traci.launcher.sumo = "sumo"
*.traci.launcher.typename = "PosixLauncher"
*.traci.launcher.sumocfg = "limassol.sumocfg"

*.node[*].wlan[*].typename = "VanetNic"
*.node[*].mobility.typename = "artery.sionna.environment.config.dynamic.SionnaVehicleActor"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
*.node[*].wlan[*].radio.transmitter.power = 200 mW
*.node[*].wlan[*].radio.antennaType = "artery.sionna.environment.radio.SionnaPlanarAntennaArray"
*.node[*].wlan[*].radio.transmitterType = "artery.sionna.environment.radio.SionnaVanetTransmitter"
*.node[*].wlan[*].radio.receiverType = "artery.sionna.environment.radio.SionnaVanetReceiver"
*.node[0].wlan[*].radio.antenna.sceneArrayRole = "tx"
*.node[1].wlan[*].radio.antenna.sceneArrayRole = "rx"
*.radioMedium.analogModelType = "artery.sionna.environment.SionnaScalarAnalogModel"
*.radioMedium.pathLossType = "artery.sionna.environment.SionnaPathLoss"

*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2013-06-01 12:35:00"
*.node[*].middleware.services = xmldoc("services.xml")

*.physicalEnvironment.typename = "artery.sionna.environment.SionnaPhysicalEnvironment"

*.physicalEnvironment.sceneConfigProvider.scenePath = "limassol-scene.xml"
*.physicalEnvironment.sceneConfigProvider.mergeMeshes = false
*.physicalEnvironment.sceneConfigProvider.mergeEquivalent = false

*.physicalEnvironment.remapMatrix = xmldoc("transforms.xml", "/transforms/sumoToSionnaRemap")
*.physicalEnvironment.rotationMatrix = xmldoc("transforms.xml", "/transforms/sumoToSionnaRotation")
*.physicalEnvironment.translationVector = xmldoc("transforms.xml", "/transforms/sumoToSionnaTranslation")

*.physicalEnvironment.sceneVisualizer.cameraConfig = xmldoc("cameras.xml")
*.physicalEnvironment.sceneVisualizer.outputDir = "results/limassol"

[Config sumo_gui]
*.traci.launcher.sumo = "sumo-gui"
