macro(get_ned_folders _target _output)
    get_target_property(_target_type ${_target} TYPE)
    if(NOT ${_target_type} STREQUAL "INTERFACE_LIBRARY")
        get_target_property(_target_ned_folders ${_target} NED_FOLDERS)
        if(_target_ned_folders)
            list(APPEND ${_output} ${_target_ned_folders})
        endif()
    endif()

    get_target_property(_target_dependencies ${_target} INTERFACE_LINK_LIBRARIES)
    if(_target_dependencies)
        foreach(_target_dependency IN LISTS _target_dependencies)
            if(TARGET ${_target_dependency})
                get_ned_folders(${_target_dependency} _target_dependency_ned_folders)
                list(APPEND ${_output} ${_target_dependency_ned_folders})
            endif()
        endforeach()
    endif()

    if(${_output})
        list(REMOVE_DUPLICATES ${_output})
    endif()
endmacro()
